### ISSUE TITLE
stream pdf directly to download

### ISSUE THREAD

**Issue by stellanhaglund** [IonicaBizau/nodeice#10]
Hi, how would I stream the pdf so that it's downloaded by the browser if I request a pdf by a post request?

I tried like this but it's not working

    app.post('/', function(req, res, next) {

      res.writeHead(200, {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename=some_file.pdf',
      'Content-Length': 1234
      });

      myInvoice.toPdf({ output: res });

      // res.end('ok');

    });

**Comment by IonicaBizau** [comment]
@stellanhaglund Define *not working*––any errors? `myInvoice.toPdf(res)` should work in the same way. 
What errors do you get?

**Comment by stellanhaglund** [comment]
I see this response in console, but the file isn't downloaded.

I'm doing a post request from another server, from the browser..

<img width="724" alt="skarmavbild 2015-12-08 kl 13 14 26" src="https://cloud.githubusercontent.com/assets/2523054/11655384/a2ce5a48-9dad-11e5-8e39-0a6edaa5f1f4.png">

**Comment by stellanhaglund** [comment]
if I set up the myInvoice.toPdf() inside a get the file is rendered in the browser, but I need to send it

**Comment by IonicaBizau** [comment]
@stellanhaglund It looks more like express stuff... Maybe if you ask a question on stackoverflow would be better. Not sure why for GET requests it works and for POST requests it doesn't... :thought_balloon:

**Comment by stellanhaglund** [comment]
I dont have to use express, do you know another way to do it that works?

tisdag 8 december 2015 skrev Ionică Bizău <notifications@github.com>:

**Comment by IonicaBizau** [comment]
@stellanhaglund [This example](https://github.com/IonicaBizau/nodeice/blob/f61750744366d37a9cfeb5f610d4b5e6d002a2a2/example/index.js#L102-L105) shows how to render it in the browser. Do you need to download instead of render it?

**Comment by stellanhaglund** [comment]
I need to download it on post requests

tisdag 8 december 2015 skrev Ionică Bizău <notifications@github.com>:

**Comment by IonicaBizau** [comment]
@stellanhaglund Tested using this:

```js
// Serve the pdf via streams (no files)
require("http").createServer(function (req, res) {

    if (req.method !== "POST") { return; }

    res.setHeader("Content-Type", "application/force-download");
    res.setHeader("Content-Transfer-Encoding", "binary");
    res.setHeader("Content-Disposition","attachment; filename=\"test.pdf\"");

    myInvoice.toPdf(res);
}).listen(8000);
```

This will download the `test.pdf` file when posting (anything) to `localhost:8000`.

**Comment by stellanhaglund** [comment]
Great thank you!!

Will it work even if the request is sent from another site using http?

tisdag 8 december 2015 skrev Ionică Bizău <notifications@github.com>:

**Comment by IonicaBizau** [comment]
@stellanhaglund Yes, of course, it's just how you send the response back to the client.
