### ISSUE TITLE
knowing when images are rendered

### ISSUE THREAD

**Issue by stellanhaglund** [IonicaBizau/nodeice#11]
Hi again, is there any way of knowing when dynamic images has finished loading in the template and make phanomtjs wait until that is done?

**Comment by IonicaBizau** [comment]
@stellanhaglund Thanks a good point! :sparkle: 

I see you already opened an issue in the relevant package: https://github.com/pofider/phantom-html-to-pdf/issues/17

I think this could be done using the `waitForJSVarName` option (by default `"PHANTOM_HTML_TO_PDF_READY"`). In your template you should have something like this:

```html
<img src="image.png" onload="window.PHANTOM_HTML_TO_PDF_READY = true">
```

**Comment by stellanhaglund** [comment]
That  could work, but is there an window object?
And say I have 10 images then that seems the variable will be true after the first image.

**Comment by IonicaBizau** [comment]
> That could work, but is there an window object?

Yes, of course, because it's a browser. :smile: 

> And say I have 10 images then that seems the variable will be true after the first image.

Then, you have to set a tiny script at the end of the HTML:

```html
<img src="1.png">
<img src="2.png">
<img src="3.png">

<script>
   function imgOnLoad(img, callback) {
     if (img.complete) {
       return callback();
     }
     img.onload = callback;
   }
   var loaded = 0;
   var allImages = document.querySelectorAll("img");

   function check(img) {
     imgOnLoad(img, function() {
       if (++loaded === allImages.length) {
         window.PHANTOM_HTML_TO_PDF_READY = true;
       }
     });
   }

   for (var i = 0; i < allImages.length; ++i) {
     check(allImages[i]);
   }
</script>
```

**Comment by stellanhaglund** [comment]
I didn't know that :) never used PhantomJS

then like this?

    ops = Ul.deepMerge(ops, {
        converter: {
            waitForJS: true,
            viewportSize: {
                width: 2480
              , height: 3508
            },
            paperSize: {
                format: "A3"
            }
        }
    });

**Comment by IonicaBizau** [comment]
Basically just like this:

```js
myInvoice.toPdf({ waitForJS: true, output: res });
```

They are merged internally.

**Comment by stellanhaglund** [comment]
If the rows in your invoice where dynamic and had images where would you place the onload script?

**Comment by IonicaBizau** [comment]
In the `index.html` file, somewhere [in the end](https://github.com/IonicaBizau/nodeice/blob/f61750744366d37a9cfeb5f610d4b5e6d002a2a2/example/template/index.html#L161). :smile:

**Comment by stellanhaglund** [comment]
I added the script after the body, and added this. myInvoice.toPdf({ waitForJS: true, output: res });

But still there is empty boxes where some images should be..

**Comment by IonicaBizau** [comment]
@stellanhaglund Can you maybe add an example? I guess it should be:

```js
myInvoice.toPdf({ converter: { waitForJS: true } , output: res });

```

**Comment by stellanhaglund** [comment]
That last one did the trick! =) awesome man, thanks!!

**Comment by IonicaBizau** [comment]
@stellanhaglund Glad to hear! :sparkle: 

If you will ever get some profit using it, [donations are always more than welcome](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RVXDDLKKLQRJW)!! :heart_decoration:
