### ISSUE TITLE
PDF Buffer

### ISSUE THREAD

**Issue by kill4food** [IonicaBizau/nodeice#21]
How can i get a PDF buffer instead of saving it to a directory?
I must use PDF and not HTML and my environment is read only, so i can't save it as file

**Comment by IonicaBizau** [comment]
There is an example already:

```sh
// Serve the pdf via streams (no files)
require("http").createServer((req, res) => {
    myInvoice.toPdf({ output: res });
}).listen(8000);
```

(using a stream)

But, you still need a writable `/tmp` folder or something like that. If it's really read-only, this won't work. It uses phantomjs to generate the pdf file.
