### ISSUE TITLE
do something with pdf

### ISSUE THREAD

**Issue by stellanhaglund** [IonicaBizau/nodeice#4]
Hi, how would I go about to do something else with the pdf than saving it in the file system, like showing it in browser or something like that?

**Comment by IonicaBizau** [comment]
That's a neat idea!

Currently the pdf can be rendered and saved on the disk, but it would be nice to stream it as pdf file in the browser. This is not possible right now.

However, what you can do is to use the `renderAsHtml`:

```js
var invoice = new Nodeice(...);
invoice.renderAsHtml({}, function (err, html) {
    response.end(html);
});
```

Didn't test, but it's supposed to work. :smile_cat:

**Comment by idlyapp** [comment]
The idea is really to create invoices from a heroku app and those have no
file system.

Then just pass it to s3 or similar, but i dont seem to be able to get hold
of the file..

fredag 7 augusti 2015 skrev Ionică Bizău <notifications@github.com>:

**Comment by IonicaBizau** [comment]
> The idea is really to create invoices from a heroku app and those have no
file system.

What do you mean they have no file system? The tmp files are still created? Or an error appears?

**Comment by idlyapp** [comment]
Im not sure about the tmp files but i cant access ./my-invoice.pdf, that
gives me an error.

For what i understand its not possible to write files and store them on
heroku

fredag 7 augusti 2015 skrev Ionică Bizău <notifications@github.com>:

**Comment by IonicaBizau** [comment]
[Yep](https://discussion.heroku.com/t/write-files-in-heroku/565). I'm working on a fix to use streams. This repository didn't get updates for a long time... Maybe because it was pretty stable. :smile:

**Comment by idlyapp** [comment]
Yes the current functionality works great and im able to do exactly what i
want running it locally.

I have no previous experience in this is it a big addon?

fredag 7 augusti 2015 skrev Ionică Bizău <notifications@github.com>:

**Comment by IonicaBizau** [comment]
@idlyapp See #5 for further reference.
