### ISSUE TITLE
More than one page

### ISSUE THREAD

**Issue by stellanhaglund** [IonicaBizau/nodeice#6]
If there is to many task rows the second page looks strange.
Have you seen this?

**Comment by IonicaBizau** [comment]
Ah, I see! The table headers are overlapping the rows. :open_mouth: 

I searched a little, and I see that this is an issue in `html-pdf` package: https://github.com/marcbachmann/node-html-pdf/issues/46

@marcbachmann @gmartini20 Any ideas how to solve this?

**Comment by IonicaBizau** [comment]
Should be fixed in **`2.0.0`**. :tada: 
Have to mention here the amazing [`phantom-html-to-pdf`](https://github.com/pofider/phantom-html-to-pdf) package by @pofider. :sparkles:
